Validate application code signature during installation.

diff --git a/macos/pkg/scripts/postinstall.in b/macos/pkg/scripts/postinstall.in
--- a/macos/pkg/scripts/postinstall.in
+++ b/macos/pkg/scripts/postinstall.in
@@ -6,14 +6,20 @@
 
 set -eu
 
+APP_DIR="$2/Mozilla VPN.app"
 LOG_DIR=/var/log/mozillavpn
+
+CODESIGN_APP_IDENTIFIER="@BUILD_OSX_APP_IDENTIFIER@"
+CODESIGN_TEAM_IDENTIFIER="@BUILD_VPN_DEVELOPMENT_TEAM@"
+CODESIGN_CERT_SUBJECT="Developer ID Application: Mozilla Corporation (${CODESIGN_TEAM_IDENTIFIER})"
 
 mkdir -p $LOG_DIR
 exec 2>&1 > $LOG_DIR/postinstall.log
 
 echo "Running postinstall at $(date)"
+echo "Installing Mozilla VPN to ${APP_DIR}"
 
-DAEMON_PLIST_PATH="/Library/LaunchDaemons/org.mozilla.macos.FirefoxVPN.daemon.plist"
+DAEMON_PLIST_PATH="/Library/LaunchDaemons/${CODESIGN_APP_IDENTIFIER}.daemon.plist"
 
 DAEMON_PLIST=$(cat <<-EOM
 <?xml version="1.0" encoding="UTF-8"?>
@@ -21,10 +27,10 @@ DAEMON_PLIST=$(cat <<-EOM
 <plist version="1.0">
         <dict>
                 <key>Label</key>
-                <string>org.mozilla.macos.FirefoxVPN.daemon</string>
+                <string>${CODESIGN_APP_IDENTIFIER}.daemon</string>
                 <key>ProgramArguments</key>
                 <array>
-                        <string>/Applications/Mozilla VPN.app/Contents/MacOS/Mozilla VPN</string>
+                        <string>${APP_DIR}/Contents/MacOS/Mozilla VPN</string>
                         <string>macosdaemon</string>
                 </array>
                 <key>UserName</key>
@@ -48,6 +54,22 @@ EOM
 pkill -x "Mozilla VPN" || echo "Unable to kill GUI, not running?"
 sleep 1
 
+## Before MacOS 13, take extra care to prevent tampering with the app.
+echo "Restrict App file permissions..."
+chown -R root "$APP_DIR"
+chmod -R go-w "$APP_DIR"
+
+echo "Validate application codesign..."
+CODESIGN_REQS="anchor apple generic"
+CODESIGN_REQS+=" and certificate leaf[subject.OU] = \"${CODESIGN_TEAM_IDENTIFIER}\""
+CODESIGN_REQS+=" and certificate leaf[subject.CN] = \"${CODESIGN_CERT_SUBJECT}\""
+if ! codesign -v --verbose=4 -R="${CODESIGN_REQS}" "$APP_DIR"; then
+  echo "Codesign failed! Aborting."
+  rm -rf "$APP_DIR"
+  exit 1
+fi
+echo "Codesign successful!"
+
 UPDATING=
 if [ -f "$DAEMON_PLIST_PATH" ]; then
   UPDATING=1
@@ -60,24 +82,24 @@ echo "$DAEMON_PLIST" > $DAEMON_PLIST_PATH
 echo "Loading the Daemon at $DAEMON_PLIST_PATH"
 launchctl load -w $DAEMON_PLIST_PATH
 
-if [ -f "/Applications/Mozilla VPN.app/Contents/Resources/utils/mozillavpn.json" ]; then
+if [ -f "${APP_DIR}/Contents/Resources/utils/mozillavpn.json" ]; then
   echo "Install the firefox native messaging manifest"
   mkdir -p "/Library/Application Support/Mozilla/NativeMessagingHosts"
-  cp -f "/Applications/Mozilla VPN.app/Contents/Resources/utils/mozillavpn.json" "/Library/Application Support/Mozilla/NativeMessagingHosts/mozillavpn.json"
+  cp -f "${APP_DIR}/Contents/Resources/utils/mozillavpn.json" "/Library/Application Support/Mozilla/NativeMessagingHosts/mozillavpn.json"
 
   echo "Install the chrome native messaging manifest"
   mkdir -p "/Library/Google/Chrome/NativeMessagingHosts"
-  cp -f "/Applications/Mozilla VPN.app/Contents/Resources/utils/mozillavpn.json" "/Library/Google/Chrome/NativeMessagingHosts/mozillavpn.json"
+  cp -f "${APP_DIR}/Contents/Resources/utils/mozillavpn.json" "/Library/Google/Chrome/NativeMessagingHosts/mozillavpn.json"
 
   echo "Install the chromium native messaging manifest"
   mkdir -p "/Library/Application Support/Chromium/NativeMessagingHosts"
-  cp -f "/Applications/Mozilla VPN.app/Contents/Resources/utils/mozillavpn.json" "/Library/Application Support/Chromium/NativeMessagingHosts/mozillavpn.json"
+  cp -f "${APP_DIR}/Contents/Resources/utils/mozillavpn.json" "/Library/Application Support/Chromium/NativeMessagingHosts/mozillavpn.json"
 fi
 
 echo "Install Complete Run the app"
 if [ "$UPDATING" ]; then
-  open -a "/Applications/Mozilla VPN.app" --args ui --updated
+  open -a "$APP_DIR" --args ui --updated
 else
-  open -a "/Applications/Mozilla VPN.app"
+  open -a "$APP_DIR"
 fi
 exit 0
