fix debug build

diff --git a/.github/workflows/macos-build.yaml b/.github/workflows/macos-build.yaml
--- a/.github/workflows/macos-build.yaml
+++ b/.github/workflows/macos-build.yaml
@@ -108,6 +108,36 @@ jobs:
           echo "GROUP_ID_IOS = group.baku.mozilla.ios.Guardian" >> xcode.xconfig
           echo "APP_ID_IOS = baku.mozilla.ios.FirefoxVPN" >> xcode.xconfig
           echo "NETEXT_ID_IOS = baku.mozilla.ios.FirefoxVPN.network-extension" >> xcode.xconfig
+          pushd glean
+          qmake -spec macx-xcode \
+            CONFIG-=debug \
+            CONFIG-=debug_and_release \
+            CONFIG+=release \
+            CONFIG+=production \
+            CONFIG+=webextension \
+            QTPLUGIN+=qsvg \
+            CONFIG-=static \
+            CONFIG+=balrog \
+            MVPN_MACOS=1 \
+            glean.pro || die "Qmake failed for glean"
+            make -j $JOBS -f glean.xcodeproj/qt_makeqmake.mak || die "Compile of Glean failed."
+            make -j $JOBS -f glean.xcodeproj/qt_preprocess.mak || die "Compile of Glean failed."
+          popd
+          pushd nebula
+          qmake -spec macx-xcode \
+            CONFIG-=debug \
+            CONFIG-=debug_and_release \
+            CONFIG+=release \
+            CONFIG+=production \
+            CONFIG+=webextension \
+            QTPLUGIN+=qsvg \
+            CONFIG-=static \
+            CONFIG+=balrog \
+            MVPN_MACOS=1 \
+            nebula.pro || die "Qmake failed for nebula"
+            make -j $JOBS -f nebula.xcodeproj/qt_makeqmake.mak || die "Compile failed for nebula."
+            make -j $JOBS -f nebula.xcodeproj/qt_preprocess.mak || die "Compile failed for nebula."
+          popd
           qmake \
             VERSION=$SHORTVERSION \
             BUILD_ID=$FULLVERSION \
