use pushd and popd

diff --git a/.github/workflows/macos-build.yaml b/.github/workflows/macos-build.yaml
--- a/.github/workflows/macos-build.yaml
+++ b/.github/workflows/macos-build.yaml
@@ -233,6 +233,7 @@ jobs:
           echo "GROUP_ID_IOS = group.org.mozilla.ios.Guardian" >> xcode.xconfig
           echo "APP_ID_IOS = org.mozilla.ios.FirefoxVPN" >> xcode.xconfig
           echo "NETEXT_ID_IOS = org.mozilla.ios.FirefoxVPN.network-extension" >> xcode.xconfig
+          pushd glean
           qmake -spec macx-xcode \
             CONFIG-=debug \
             CONFIG-=debug_and_release \
@@ -243,9 +244,11 @@ jobs:
             CONFIG-=static \
             CONFIG+=balrog \
             MVPN_MACOS=1 \
-            glean/glean.pro || die "Qmake failed for glean"
-            make -C glean/ -j $JOBS -f glean.xcodeproj/qt_makeqmake.mak || die "Compile of Glean failed."
-            make -C glean/ -j $JOBS -f glean.xcodeproj/qt_preprocess.mak || die "Compile of Glean failed."
+            glean.pro || die "Qmake failed for glean"
+            make -j $JOBS -f glean.xcodeproj/qt_makeqmake.mak || die "Compile of Glean failed."
+            make -j $JOBS -f glean.xcodeproj/qt_preprocess.mak || die "Compile of Glean failed."
+          popd
+          pushd nebula
           qmake -spec macx-xcode \
             CONFIG-=debug \
             CONFIG-=debug_and_release \
@@ -256,9 +259,10 @@ jobs:
             CONFIG-=static \
             CONFIG+=balrog \
             MVPN_MACOS=1 \
-            nebula/nebula.pro || die "Qmake failed for nebula"
-            make -C nebula/ -j $JOBS -f nebula.xcodeproj/qt_makeqmake.mak || die "Compile failed for nebula."
-            make -C nebula/ -j $JOBS -f nebula.xcodeproj/qt_preprocess.mak || die "Compile failed for nebula."
+            nebula.pro || die "Qmake failed for nebula"
+            make -j $JOBS -f nebula.xcodeproj/qt_makeqmake.mak || die "Compile failed for nebula."
+            make -j $JOBS -f nebula.xcodeproj/qt_preprocess.mak || die "Compile failed for nebula."
+          popd
           qmake \
             VERSION=$SHORTVERSION \
             BUILD_ID=$FULLVERSION \
