try something else

diff --git a/.github/workflows/macos-build.yaml b/.github/workflows/macos-build.yaml
--- a/.github/workflows/macos-build.yaml
+++ b/.github/workflows/macos-build.yaml
@@ -233,7 +233,6 @@ jobs:
           echo "GROUP_ID_IOS = group.org.mozilla.ios.Guardian" >> xcode.xconfig
           echo "APP_ID_IOS = org.mozilla.ios.FirefoxVPN" >> xcode.xconfig
           echo "NETEXT_ID_IOS = org.mozilla.ios.FirefoxVPN.network-extension" >> xcode.xconfig
-          pushd glean
           qmake -spec macx-xcode \
             CONFIG-=debug \
             CONFIG-=debug_and_release \
@@ -244,11 +243,9 @@ jobs:
             CONFIG-=static \
             CONFIG+=balrog \
             MVPN_MACOS=1 \
-            glean.pro || die "Qmake failed for glean"
-            make -j $JOBS -f glean.xcodeproj/qt_makeqmake.mak || die "Compile of Glean failed."
-            make -j $JOBS -f glean.xcodeproj/qt_preprocess.mak || die "Compile of Glean failed."
-          popd
-          pushd nebula
+            glean/glean.pro || die "Qmake failed for glean"
+            make -C glean/ -j $JOBS -f glean.xcodeproj/qt_makeqmake.mak || die "Compile of Glean failed."
+            make -C glean/ -j $JOBS -f glean.xcodeproj/qt_preprocess.mak || die "Compile of Glean failed."
           qmake -spec macx-xcode \
             CONFIG-=debug \
             CONFIG-=debug_and_release \
@@ -259,10 +256,9 @@ jobs:
             CONFIG-=static \
             CONFIG+=balrog \
             MVPN_MACOS=1 \
-            nebula.pro || die "Qmake failed for nebula"
-            make -j $JOBS -f nebula.xcodeproj/qt_makeqmake.mak || die "Compile failed for nebula."
-            make -j $JOBS -f nebula.xcodeproj/qt_preprocess.mak || die "Compile failed for nebula."
-          popd
+            nebula/nebula.pro || die "Qmake failed for nebula"
+            make -C nebula/ -j $JOBS -f nebula.xcodeproj/qt_makeqmake.mak || die "Compile failed for nebula."
+            make -C nebula/ -j $JOBS -f nebula.xcodeproj/qt_preprocess.mak || die "Compile failed for nebula."
           qmake \
             VERSION=$SHORTVERSION \
             BUILD_ID=$FULLVERSION \
